package enumeration;

/**
 *
 * @author Qiang
 * @date 2016年4月9日
 */
public enum API_TYPE {
	GET_BENCHMARK_MES, IS_TRADING_DAY, GET_STOCKMES_AT_TIME, GET_TIMESAHRING, CHECK_IF_TRADING,
	
	
	
	GET_STOCKS_LIST , GET_STOCKS_LIST_WITH_EXCHANGE;
}
